services:
  postgresql:
    platform: linux/arm64
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: goliath
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d goliath -U user"]
      interval: 5s
      retries: 5
    # ports:
    #   - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - postgresql
  #   ports:
  #     - 8082:8080

  s3storage:
    platform: linux/arm64
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      AWS_REGION: us-east-1
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    ports:
      # - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  # redis:
  #   platform: linux/arm64
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

volumes:
  minio-data:
  pg-data:
